@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(mvUser, "Usuário Movve", "Usuário que faz parte do time da Movve")
Person(masterUser, "Usuário Master", "Dono de uma conta que a gerencia, cria perfis, gamifica.")
Person(usuarioEmpresa, "Usuário Empresa", "Usuário que possui um perfil de acesso para gerenciar, gamificar ou visualizar dashboards.")
Person(jogador, "Jogador", "Usuário que participa de um jogo.")

System(mvStudio, "Frontend Movve Studio", "Disponibiliza um CRM para gerenciamento de contas, usuários, gamificações e jogos.")
System(mvFramework, "Backend Movve Framework", "API de gamificação generica.")
System(app, "Mobile App", "Aplicativos feitos sob medida para um modelo de jogo específico.")

Rel(mvUser, mvStudio, "Interage com via", "HTTPS")
Rel(masterUser, mvStudio, "Interage com via", "HTTPS")
Rel(usuarioEmpresa, mvStudio, "Interage com via", "HTTPS")
Rel(jogador, app, "Interage com via", "Aplicação")

Rel(mvStudio, mvFramework, "Interage com via", "HTTPS/JSON")
Rel(app, mvFramework, "Interage com via", "HTTPS/JSON")

@enduml